vuestorefront-community/prestashop

.github/workflows/docs-deployment.yaml
.vuestorefrontcloud/docker/docs/Dockerfile
.vuestorefrontcloud/docker/docs/build-docker.sh

chore: updated documentation deployment

---

packages/api-client/src/api/fetchOrders/index.ts
packages/api-client/src/api/index.ts
packages/composables/src/getters/orderGetters.ts
packages/composables/src/helpers/index.ts
packages/composables/src/helpers/populateOrderDetails.ts
packages/composables/src/helpers/populateOrdersList.ts
packages/composables/src/useUserOrder/index.ts
packages/theme/components/OrderItems.vue
packages/theme/pages/MyAccount/OrderHistory.vue

Order history

---

packages/theme/pages/MyAccount.vue

fix myaccount items

---

packages/composables/src/useUserOrder/index.ts

+ Fix orders list bug

---

packages/theme/components/AddressForm.vue
packages/theme/components/Checkout/VsfShippingProvider.vue
packages/theme/pages/Checkout/Payment.vue
packages/theme/pages/Checkout/Shipping.vue

+ Fix some shipping styling
+ Fix selected address visibility
+ Better performance for select shipping provider

Fix some checkout bugs

---

.husky/commit-msg
.husky/pre-commit
.husky/prepare-commit-msg
packages/api-client/src/api/index.ts
packages/api-client/src/api/makeOrder/index.ts
packages/composables/src/helpers/populatePaymentProvidersList.ts
packages/composables/src/helpers/populateShippingProvidersList.ts
packages/composables/src/useMakeOrder/index.ts
packages/composables/src/usePayment/index.ts
packages/theme/components/AddressForm.vue
packages/theme/components/Checkout/VsfPaymentProvider.vue
packages/theme/components/Checkout/VsfShippingProvider.vue
packages/theme/pages/Checkout/Payment.vue
packages/theme/pages/Checkout/Shipping.vue

+ Fix checkout bug

---

packages/composables/src/getters/cartGetters.ts

+ Fix card total price bug

---

packages/theme/lang/de.js
packages/theme/lang/es.js
packages/theme/lang/fr.js
packages/theme/lang/it.js
packages/theme/lang/pt.js

Translation add cart

---

README.md

Fix discord support link

---

packages/composables/src/useBootstrap/index.ts
packages/composables/src/useCountryList/index.ts
packages/composables/src/usePayment/index.ts
packages/theme/components/AddressForm.vue

fix: fix for locale and currency cookies

---

packages/composables/src/getters/cartGetters.ts
packages/composables/src/helpers/populateShippingProvidersList.ts
packages/theme/components/Checkout/CartPreview.vue
packages/theme/components/Checkout/VsfShippingProvider.vue

feat: added shipping price to delivery option and cart preview

---

packages/composables/src/useShippingProvider/index.ts
packages/theme/components/Checkout/VsfShippingProvider.vue

issue: https://github.com/vuestorefront-community/prestashop/issues/70

+ Fix an issue where the shipping option was not set correctly

---

packages/theme/components/AppHeader.vue

fix: fixed lang selector is showing on mobile in single lang

---

packages/composables/src/getters/cartGetters.ts
packages/theme/components/CartSidebar.vue

Handling cart errors like processing out-of-stock products in cart.

[Feature] Handling cart errors

---

packages/theme/components/FiltersSidebar.vue

+fix set filters issue
issue: https://github.com/vuestorefront-community/prestashop/issues/82

Fix Filters checkboxes not showing current state 

---

packages/api-client/src/api/getProduct/index.ts
packages/composables/src/index.ts
packages/composables/src/useCheckProduct/index.ts
packages/theme/components/CartSidebar.vue
packages/theme/pages/Product.vue

Stop adding out of stock product in product detail page, 
- checks product availability on every spin up and down
- it supports both combinations and standard products
Allows adding unlimited number of products: https://github.com/vuestorefront-community/prestashop/issues/74
https://user-images.githubusercontent.com/20775532/213931697-44d9ba30-3206-4310-a6f9-210a0750f7a2.mp4

[Feature] Stop adding out of stock product

---

packages/composables/src/getters/cartGetters.ts

[Fix] cart error null bug fixed

---

packages/theme/pages/MyAccount/OrderHistory.vue

[Fix] orders history start shopping button link

---

packages/composables/src/getters/facetGetters.ts
packages/composables/src/helpers/populateCategoryProducts.ts
yarn.lock

[Fix]: added  product.quantity to populateCategoryProduct

---

packages/composables/src/useBootstrap/index.ts
packages/composables/src/useCart/index.ts
packages/composables/src/useCheckProduct/index.ts
packages/composables/src/useCountryList/index.ts
packages/composables/src/useFacet/index.ts
packages/composables/src/useMakeOrder/index.ts
packages/composables/src/usePayment/index.ts
packages/composables/src/useProduct/index.ts
packages/composables/src/useReview/index.ts
packages/composables/src/useShippingProvider/index.ts
packages/composables/src/useUser/index.ts
packages/composables/src/useUserOrder/index.ts
packages/composables/src/useUserShipping/index.ts

[Fix] undefined locale in multi language

---

packages/theme/components/AddressForm.vue

[Fix]: fix for empty zip-code format 

---

packages/api-client/src/api/getAvailableCountries/index.ts
packages/composables/src/helpers/populateCountriesList.ts
packages/theme/components/AddressForm.vue

[Feat] added address identification number

---

packages/theme/components/CartSidebar.vue

fix: fixed discounts in cart items

---

packages/theme/components/Checkout/VsfShippingProvider.vue
packages/theme/lang/cz.js
packages/theme/lang/de.js
packages/theme/lang/en.js
packages/theme/lang/es.js
packages/theme/lang/fr.js
packages/theme/lang/it.js
packages/theme/lang/pt.js

[Feat] added no carriers message

---

packages/theme/pages/Product.vue

remove loading on attribute changes
